export const GET_CATEGORIES = "GET_CATEGORIES";
export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const GET_INCI = "GET_INCI";
export const GET_INCI_SUCCESS = "GET_INCI_SUCCESS";
export const CHANGE_DRAWER_STATUS = "CHANGE_DRAWER_STATUS";
export const LOGOUT = "LOGOUT";
export const SELECTED_ENTRY = "SELECTED_ENTRY";